
# mysite.loc 80
server {
    listen 80;
    server_name mysite.loc;
    location / {
        proxy_pass http://mysite.loc:8080/;
    }
}

# mysite2.loc 8010 / 44310
server {
    listen 80;
    listen [::]:80;
    server_name mysite2.loc;
    location / {
        proxy_pass http://mysite2.loc:8010/;
    }
}
server {
    listen 443;
    listen [::]:443;
    server_name mysite2.loc;
    location / {
        proxy_ssl_verify off;
        proxy_pass https://mysite2.loc:44310;
        proxy_ssl_certificate         /var/SSL/mysite2.loc/mysite2.loc.crt;
        proxy_ssl_certificate_key     /var/SSL/mysite2.loc/mysite2.loc.key;
        proxy_ssl_trusted_certificate /var/SSL/ROOT_CA_CERT/myRootCA.pem;
    }
}
